stages:
  - stage: PublishPackages
    displayName: 'Publish Artifacts'
    jobs:
      - job: PublishUsingPMC_MI
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - task: PipAuthenticate@1
            displayName: 'Pip Authenticate'
            inputs:
              artifactFeeds: 'One/AzFilesAuthenticator'
          
          # download artifacts that need to be published
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Signed Artifacts'
            inputs:
                buildType: 'specific'
                project: 'b32aa71e-8ed2-41b2-9d77-5bc261222004'
                pipeline: 'azfilesauthenticator'
                buildVersionToDownload: 'latest'
                downloadType: 'single'
                ArtifactName: 'azfilesauth-signed'
                downloadPath: $(Build.ArtifactStagingDirectory)

          - script: |
                set -x
                ls $(Build.ArtifactStagingDirectory)
                
          - task: AzureCLI@2
            displayName: 'Publish Packages'
            inputs:
              addSpnToEnvironment: true
              azureSubscription: 'AzFilesAuthenticator-wif'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Build.ArtifactStagingDirectory)/azfilesauth-signed
              inlineScript: |
                set -x
                set -euo pipefail
                
                echo "1) Installing pmc-cli"
                pip install pmc-cli
                pmc --version

                PMC_BASE_URL="https://pmc-ingest.trafficmanager.net/api/v4"
                # For test/debug: 
                # PMC="echo pmc --auth-type wif --base-url $PMC_BASE_URL"
                PMC="pmc --auth-type wif --base-url $PMC_BASE_URL"
                $PMC repo list --path-contains "noble"

                publish_package() {
                  local pkg_file="$1"
                  local repo_name="$2"
                  local release_name="${3:-}"

                  echo "Uploading $pkg_file to PMC..."
                  PKG_ID=$($PMC --id-only package upload "$pkg_file") || {
                    echo "Failed to upload $pkg_file"
                    exit 1
                  }

                  if [ -n "$release_name" ]; then
                    echo "Adding package $PKG_ID to repo $repo_name (release=$release_name)"
                    $PMC repo package update --add-packages "$PKG_ID" "$repo_name" "$release_name"
                  else
                    echo "Adding package $PKG_ID to repo $repo_name"
                    $PMC repo package update --add-packages "$PKG_ID" "$repo_name"
                  fi

                  echo "Publishing repo $repo_name"
                  $PMC repo publish "$repo_name"
                }

                # publish_package *.focal.deb microsoft-ubuntu-focal-prod-apt focal
                # publish_package *.jammy.deb microsoft-ubuntu-jammy-prod-apt jammy
                # publish_package *.noble.deb microsoft-ubuntu-noble-prod-apt noble
                # publish_package *azl3*.rpm azurelinux-3.0-prod-ms-oss-x86_64-yum
