resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

  pipelines:
    - pipeline: azfilesauthenticator
      source: azfilesauthenticator
      trigger: none
      project: One
      branch: azure-pipelines-ev2
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    stages:
    # - stage: 'Get_Artifacts'
    #   displayName: 'Obtaining EV2 artifacts'
    #   dependsOn: []
    #   jobs:
    #   - job: PublishUsingPMC_MI
    #     pool:
    #       vmImage: 'ubuntu-22.04'
    #     steps:
    #       - task: PipAuthenticate@1
    #         displayName: 'Pip Authenticate'
    #         inputs:
    #           artifactFeeds: 'One/AzFilesAuthenticator'
          
    #       # download artifacts that need to be published
    #       - task: DownloadPipelineArtifact@2
    #         displayName: 'Download Signed Artifacts'
    #         inputs:
    #             buildType: 'specific'
    #             project: 'b32aa71e-8ed2-41b2-9d77-5bc261222004'
    #             pipeline: 'azfilesauthenticator'
    #             buildVersionToDownload: 'latest'
    #             allowFailedBuilds: true
    #             allowPartiallySucceededBuilds: true
    #             ArtifactName: 'azfilesauth-signed'
    #             downloadPath: $(Build.ArtifactStagingDirectory)/azfilesauth-signed
      
    - stage: 'Prod_Deploy'      
      displayName: 'Deployment to production'
      dependsOn: []
      variables:
        ob_release_environment: Production
      jobs:  
      - job: ReleaseJob
        displayName: "Release Job"
        # templateContext: # We highly recommend downloading artifacts by specifying the artifact via template context inputs. This is in line with how artifacts are downloaded in other release categories and will auto-inject SBOM validation.
        #     inputs:
        #       - input: azfilesauthenticator
        #         pipeline: azfilesauthenticator
        #         artifactName: EV2_PMC
        pool:          
          type: release
        steps:
          - download: EV2_PMC
          - task: vsrm-ev2.vss-services-ev2.adm-release-task.ExpressV2Internal@1
            inputs:
              UseServerMonitorTask: false
              EnableStrictValidation: false
              ValidateOnly: false
              EndpointProviderType: ApprovalService
              ApprovalServiceEnvironment: Production
              ServiceRootLocation: 'LinkedArtifact'
              RolloutSpecType: 'RSPath'
              ServiceRootPath: '$(Pipeline.Workspace)/EV2_PMC/ServiceGroupRoot'
              RolloutSpecPath: '$(Pipeline.Workspace)/EV2_PMC/ServiceGroupRoot/RolloutSpec.Prod.json'
