trigger:
- none

pr:
- none

variables:
- name: checkoutBranch
  value: release7

stages:
  - stage: TestCommands
    displayName: 'Testing Commands (Not required stage)'
    jobs:
    - job: Test
      displayName: 'Testing'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - script: |
            set -x
            test_fun() {
              echo "Running from test function"
            }
            test_fun
          displayName: 'Build DEB Package'

  - stage: BuildPackages
    displayName: 'Build and Package DEB/RPM Artifacts'
    jobs:
    - job: BuildDEB
      displayName: 'Build DEB'
      strategy:
        matrix:
          ubuntu20:
            containerImage: ubuntu:20.04
            releaseName: 'focal'
          ubuntu22:
            containerImage: ubuntu:22.04 
            releaseName: 'jammy'
          ubuntu24:
            containerImage: ubuntu:24.04
            releaseName: 'noble'
      
      container: $(containerImage)
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          path: AzFilesAuthenticator
          displayName: 'Checkout Repository'

        - script: |
            set -x
            chmod +x package-deb.sh
            ./package-deb.sh $(releaseName)
          displayName: 'Build DEB Package'

        - script: |
            set -x
            mkdir -p $(Build.ArtifactStagingDirectory)/$[ matrix.releaseName ]
            cp PACKAGES/deb/*.deb $(Build.ArtifactStagingDirectory)/$[ matrix.releaseName ]
          displayName: 'Stage DEB Package'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$[ matrix.releaseName ]'
            ArtifactName: 'azfilesauth-deb'


    - job: BuildAzLinuxRPM
      displayName: 'Build RPM for Azure Linux 3'
      pool:
        name: 'azfilesauth-1es-pool'

      steps:
        - checkout: self
          path: AzFilesAuthenticator
          displayName: 'Checkout Repository'

        - script: |
            set -x
            git branch
            git checkout $(checkoutBranch)
            git --no-pager log -n 5
            echo "Building RPM (AzLinux) package..."
            chmod +x package-azlinux.sh
            ./package-azlinux.sh
          displayName: 'Build RPM (AzLinux) Package'

        - script: |
            set -x
            pwd
            echo "Copying RPM package to artifacts..."
            mkdir -p $(Build.ArtifactStagingDirectory)
            rm PACKAGES/rpm/*debuginfo*
            cp PACKAGES/rpm/*.rpm $(Build.ArtifactStagingDirectory)
            echo "Listing Built Files..."
            ls -R $(Build.ArtifactStagingDirectory)
          displayName: 'Copy RPM (AzLinux) Package to Artifacts'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'azfilesauth-rpm'



  - stage: SignArtifacts
    displayName: 'Sign Artifacts'
    dependsOn: BuildPackages
    condition: succeeded('BuildPackages')
    jobs:
      - job: SignArtifacts
        timeoutInMinutes: 120

        pool:
          vmImage: 'ubuntu-22.04'

        steps:
          - checkout: none

          # download artifacts that need to be published
          - task: DownloadBuildArtifacts@1
            displayName: 'Download DEB Artifacts'
            inputs:
              ArtifactName: 'azfilesauth-deb'
              downloadPath: $(Build.ArtifactStagingDirectory)

          - task: DownloadBuildArtifacts@1
            displayName: 'Download RPM Artifacts'
            inputs:
              ArtifactName: 'azfilesauth-rpm'
              downloadPath: $(Build.ArtifactStagingDirectory)

          - script: |
              set -x
              sudo ls -lRt $(Build.ArtifactStagingDirectory)
            displayName: 'List Artifacts'

          - script: |
              set -x
              sudo apt -y update
              wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
              sudo dpkg -i packages-microsoft-prod.deb
              sudo apt update
              sudo apt install apt-transport-https -y
              sudo apt install dotnet-sdk-9.0 -y
            displayName: "Update dependencies"
          
          - task: EsrpCodeSigning@5
            displayName: 'ESRP CodeSigning MI DEB'
            inputs:
              ConnectedServiceName: 'AzFilesAuthenticator-wif'
              AppRegistrationClientId: '$(AppRegistrationClientId)'
              AppRegistrationTenantId: '$(AppRegistrationTenantId)'
              EsrpClientId: '$(AppRegistrationClientId)'
              UseMSIAuthentication: true
              AuthAKVName: '$(AuthAKVName)'
              AuthSignCertName: '$(AuthSignCertName)'
              FolderPath: '$(Build.ArtifactStagingDirectory)/azfilesauth-deb'
              Pattern: '*.deb'
              signConfigType: 'inlineSignParams'
              inlineOperation: |
                [
                {
                  "KeyCode": "CP-450779-Pgp",
                  "OperationCode": "LinuxSign",
                  "ToolName": "sign",
                  "ToolVersion": "1.0",
                  "Parameters": {}
                }
                ]
              SessionTimeout: '90'
              MaxConcurrency: '25'
              MaxRetryAttempts: '5'
              PendingAnalysisWaitTimeoutMinutes: '5'
              VerboseLogin: true

          - task: EsrpCodeSigning@5
            displayName: 'ESRP CodeSigning MI AzLinux3 RPM'
            inputs:
              ConnectedServiceName: 'AzFilesAuthenticator-wif'
              AppRegistrationClientId: '$(AppRegistrationClientId)'
              AppRegistrationTenantId: '$(AppRegistrationTenantId)'
              EsrpClientId: '$(AppRegistrationClientId)'
              UseMSIAuthentication: true
              AuthAKVName: '$(AuthAKVName)'
              AuthSignCertName: '$(AuthSignCertName)'
              FolderPath: '$(Build.ArtifactStagingDirectory)/azfilesauth-rpm'
              Pattern: '*azl3*.rpm'
              signConfigType: 'inlineSignParams'
              inlineOperation: |
                [
                {
                  "KeyCode": "CP-459159-Pgp",
                  "OperationCode": "LinuxSign",
                  "ToolName": "sign",
                  "ToolVersion": "1.0",
                  "Parameters": {}
                }
                ]
              SessionTimeout: '90'
              MaxConcurrency: '25'
              MaxRetryAttempts: '5'
              PendingAnalysisWaitTimeoutMinutes: '5'
              VerboseLogin: true


          # - task: EsrpCodeSigning@5
          #   displayName: 'ESRP CodeSigning MI RPM'
          #   inputs:
          #     ConnectedServiceName: 'AzFilesAuthenticator-wif'
          #     AppRegistrationClientId: $(AppRegistrationClientId)
          #     AppRegistrationTenantId: $(AppRegistrationTenantId)

          #     UseMSIAuthentication: true
          #     AuthAKVName: $(AuthAKVName)
          #     AuthSignCertName: $(AuthSignCertName)

          #     FolderPath: $(Build.ArtifactStagingDirectory)/azfilesauth-rpm
          #     Pattern: '*.rpm'
          #     SessionTimeout: 90
          #     ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2'
          #     MaxConcurrency: 25
          #     signConfigType: inlineSignParams
          #     VerboseLogin: true
          #     inlineOperation: |
          #       [
          #       {
          #         "KeyCode": "CP-450779-Pgp",
          #         "OperationCode": "LinuxSign",
          #         "ToolName": "sign",
          #         "ToolVersion": "1.0",
          #         "Parameters": {}
          #       }
          #       ]

          - script: |
              set -x
              echo "Listing unsigned artifacts in the staging directory..."
              ls $(Build.ArtifactStagingDirectory)
              chmod 755 $(Build.ArtifactStagingDirectory)/azfilesauth-deb/*.deb
              chmod 755 $(Build.ArtifactStagingDirectory)/azfilesauth-rpm/*.rpm
              mkdir -p $(Build.ArtifactStagingDirectory)/signed
              cp $(Build.ArtifactStagingDirectory)/azfilesauth-deb/*.deb $(Build.ArtifactStagingDirectory)/signed
              cp $(Build.ArtifactStagingDirectory)/azfilesauth-rpm/*.rpm $(Build.ArtifactStagingDirectory)/signed
            displayName: 'Prepare Signed Artifacts'
          
          - script: |
              set -x
              echo "Listing Signed Artifacts..."
              ls -R $(Build.ArtifactStagingDirectory)/signed/
            displayName: 'List Signed Artifacts'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Signed Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/signed'
              ArtifactName: 'azfilesauth-signed'

  - stage: PublishPackages
    displayName: 'Publish Artifacts'
    dependsOn: SignArtifacts
    condition: succeeded('SignArtifacts')
    jobs:
      - job: PublishUsingPMC_MI
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - task: PipAuthenticate@1
            displayName: 'Pip Authenticate'
            inputs:
              artifactFeeds: 'One/AzFilesAuthenticator'
          
          # download artifacts that need to be published
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Signed Artifacts'
            inputs:
              ArtifactName: 'azfilesauth-signed'
              downloadPath: $(Build.ArtifactStagingDirectory)

          - task: AzureCLI@2
            displayName: 'Publish Packages'
            inputs:
              addSpnToEnvironment: true
              azureSubscription: 'AzFilesAuthenticator-wif'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Build.ArtifactStagingDirectory)/azfilesauth-signed
              inlineScript: |
                set -x
                set -euo pipefail
                
                echo "1) Installing pmc-cli"
                pip install pmc-cli
                pmc --version

                PMC_BASE_URL="https://pmc-ingest.trafficmanager.net/api/v4"
                # For test/debug: 
                # PMC="echo pmc --auth-type wif --base-url $PMC_BASE_URL"
                PMC="pmc --auth-type wif --base-url $PMC_BASE_URL"

                publish_package() {
                  local pkg_file="$1"
                  local repo_name="$2"
                  local release_name="${3:-}"

                  echo "Uploading $pkg_file to PMC..."
                  PKG_ID=$($PMC --id-only package upload "$pkg_file") || {
                    echo "Failed to upload $pkg_file"
                    exit 1
                  }

                  if [ -n "$release_name" ]; then
                    echo "Adding package $PKG_ID to repo $repo_name (release=$release_name)"
                    $PMC repo package update --add-packages "$PKG_ID" "$repo_name" "$release_name"
                  else
                    echo "Adding package $PKG_ID to repo $repo_name"
                    $PMC repo package update --add-packages "$PKG_ID" "$repo_name"
                  fi

                  echo "Publishing repo $repo_name"
                  $PMC repo publish "$repo_name"
                }

                publish_package *.focal.deb microsoft-ubuntu-focal-prod-apt focal
                publish_package *.jammy.deb microsoft-ubuntu-jammy-prod-apt jammy
                publish_package *.noble.deb microsoft-ubuntu-noble-prod-apt noble
                publish_package *azl3*.rpm azurelinux-3.0-prod-ms-oss-x86_64-yum

                # echo "Looking for .deb files..."
                # for PKG_FILE in *.deb; do
                #   [ -e "$PKG_FILE" ] || { echo "No .deb files found. Skipping APT upload."; break; }

                #   echo "Uploading $PKG_FILE to PMC..."
                #   PKG_ID=$($PMC --id-only package upload "$PKG_FILE") || {
                #     echo "Failed to upload $PKG_FILE"
                #     exit 1
                #   }

                #   echo "Adding package $PKG_ID to repo microsoft-ubuntu-jammy-prod-apt"
                #   $PMC repo package update --add-packages "$PKG_ID" microsoft-ubuntu-jammy-prod-apt jammy

                #   echo "Publishing repo microsoft-ubuntu-jammy-prod-apt"
                #   $PMC repo publish microsoft-ubuntu-jammy-prod-apt
                # done

                # echo "Looking for azl3 RPM files..."
                # for PKG_FILE in *azl3*.rpm; do
                #   [ -e "$PKG_FILE" ] || { echo "No matching RPM files found. Skipping YUM upload."; break; }

                #   echo "Uploading $PKG_FILE to PMC..."
                #   PKG_ID=$($PMC --id-only package upload "$PKG_FILE") || {
                #     echo "Failed to upload $PKG_FILE"
                #     exit 1
                #   }

                #   echo "Adding package $PKG_ID to repo azurelinux-3.0-prod-ms-oss-x86_64-yum"
                #   $PMC repo package update --add-packages "$PKG_ID" azurelinux-3.0-prod-ms-oss-x86_64-yum

                #   echo "Publishing repo azurelinux-3.0-prod-ms-oss-x86_64-yum"
                #   $PMC repo publish azurelinux-3.0-prod-ms-oss-x86_64-yum
                # done

                # echo "Done publishing packages."




      # - job: BuildEV2Artifacts
      #   timeoutInMinutes: 120

      #   pool:
      #     vmImage: 'ubuntu-22.04'
      #     # container: ubuntu:20.04

      #   steps:
      #     - checkout: self
      #       path: AzFilesAuthenticator
      #       displayName: 'Checkout Repository'

      #     # download artifacts that need to be published
      #     - task: DownloadBuildArtifacts@1
      #       displayName: 'Download Signed Artifacts'
      #       inputs:
      #         ArtifactName: 'azfilesauth-signed'
      #         downloadPath: $(Build.ArtifactStagingDirectory)

      #     - task: UsePythonVersion@0
      #       displayName: 'Use Python 3.8'
      #       inputs:
      #         versionSpec: 3.8

      #     - task: PipAuthenticate@1
      #       displayName: 'Pip Authenticate'
      #       inputs:
      #         artifactFeeds: 'One/AzFilesAuthenticator'
          
          
      #     - task: DownloadSecureFile@1
      #       name: settings
      #       inputs:
      #         secureFile: 'AzFilesAuthenticator_settings.toml'
      #       displayName: 'Download PMC Config File'

      #     - task: DownloadSecureFile@1
      #       name: serviceModel
      #       inputs:
      #        secureFile: 'AzFilesAuthenticator_ServiceModel.Prod.json'
      #       displayName: 'Download EV2 Scope Bindings'

      #     - task: DownloadSecureFile@1
      #       name: scopebindings
      #       inputs:
      #        secureFile: 'AzFilesAuthenticator_scopebindings.json'
      #       displayName: 'Download EV2 Scope Bindings'

      #     - bash: |
      #         EV2_DIR="$(Build.SourcesDirectory)/deploy/EV2_PMC"
      #         SHEXT_BUNDLE_DIR="$EV2_DIR/ServiceGroupRoot/Packages/ShellExt"
      #         cp $(scopebindings.secureFilePath) "$EV2_DIR/ServiceGroupRoot/ScopeBindings.Prod.json"
      #         cp $(serviceModel.secureFilePath) "$EV2_DIR/ServiceGroupRoot/ServiceModel.Prod.json"
              
      #         echo "1) Get pmc-cli"
      #         cd "$SHEXT_BUNDLE_DIR"
      #         mkdir python_dl
      #         pip3 download -d python_dl pmc-cli 
      #         # --python-version 3.8 --implementation cp --platform manylinux2014_x86_64 --abi cp38

      #         echo "2) Copy built DEB packages"
      #         # assuming ESRP signed packages are here:
      #         cd "$(Build.ArtifactStagingDirectory)/azfilesauth-signed"
      #         mkdir "$SHEXT_BUNDLE_DIR/packages"
      #         cp -v *.deb "$SHEXT_BUNDLE_DIR/packages/"

      #         echo "3) Archive for the ShellExt bundle"
      #         cd "$SHEXT_BUNDLE_DIR"
      #         cp $(settings.secureFilePath) ./settings.toml
      #         tar cvf pmc_packages.tar start.sh settings.toml packages python_dl
      #         ls -al

      #         echo "4) Copy EV2 files to artifacts staging"
      #         cp -rv "$EV2_DIR" "$(Build.ArtifactStagingDirectory)/"

      #     - task: PublishBuildArtifacts@1
      #       displayName: 'Publish EV2_PMC Artifacts'
      #       inputs:
      #         PathtoPublish: '$(Build.ArtifactStagingDirectory)/EV2_PMC'
      #         ArtifactName: 'EV2_PMC'

      # - job: Ev2Rollout
      #   displayName: 'EV2 Rollout'
      #   pool: 
      #     type: release
      #   dependsOn: BuildEV2Artifacts
      #   steps:
      #     - task: DownloadBuildArtifacts@1
      #       displayName: 'Download PMC Artifacts'
      #       inputs:
      #         ArtifactName: 'ev2_pmc'
      #         downloadPath: $(Build.ArtifactStagingDirectory)
      #     - task: Ev2RARollout@2
      #       inputs:
      #         EndpointProviderType: 'ApprovalService'
      #         ApprovalServiceEnvironment: 'Production'
      #         TaskAction: 'registerAndRollout'
      #         ServiceRootLocation: 'LinkedArtifact'
      #         ServiceRootPath: '$(Build.ArtifactStagingDirectory)/EV2_PMC/ServiceGroupRoot'
      #         RolloutSpecPath: '$(Build.ArtifactStagingDirectory)/EV2_PMC/ServiceGroupRoot/RolloutSpec.Prod.json'
      #         StageMapName: 'Microsoft.Azure.SDP.Standard'
      #         Select: regions('northeurope')
      #         UseServerMonitorTask: true
      #         ValidateOnly: false
              


  
