trigger:
- none

pr:
- none


stages:
  - stage: BuildPackages
    displayName: 'Build and Package DEB/RPM Artifacts'
    jobs:
    - job: BuildDEB
      displayName: 'Build DEB'
      pool:
        vmImage: 'ubuntu-22.04'

      steps:
        - checkout: self
          path: AzFilesAuthenticator
          displayName: 'Checkout Repository'

        - script: |
            echo "Building DEB package..."
            chmod +x package-deb.sh
            ./package-deb.sh
          displayName: 'Build DEB Package'

        - script: |
            echo "Copying DEB package to artifacts..."
            mkdir -p $(Build.ArtifactStagingDirectory)
            cp PACKAGES/deb/*.deb $(Build.ArtifactStagingDirectory)
            echo "Listing Built Files..."
            ls -R $(Build.ArtifactStagingDirectory)
          displayName: 'Copy DEB Package to Artifacts'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'azfilesauth-deb'

    # - job: BuildRPM
    #   displayName: 'Build RPM'
    #   pool:
    #     vmImage: 'ubuntu-latest'

    #   steps:
    #     - checkout: self
    #       path: AzFilesAuthenticator
    #       displayName: 'Checkout Repository'

    #     - script: |
    #         sudo apt-get install rpm -y
    #         echo "Building RPM package..."
    #         chmod +x package-rpm.sh
    #         ./package-rpm.sh
    #       displayName: 'Build RPM Package'

    #     - script: |
    #         echo "Copying RPM package to artifacts..."
    #         mkdir -p $(Build.ArtifactStagingDirectory)
    #         cp PACKAGES/rpm/*.rpm $(Build.ArtifactStagingDirectory)
    #         echo "Listing Built Files..."
    #         ls -R $(Build.ArtifactStagingDirectory)
    #       displayName: 'Copy RPM Package to Artifacts'

    #     - task: PublishBuildArtifacts@1
    #       displayName: 'Publish RPM Package'
    #       inputs:
    #         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #         ArtifactName: 'azfilesauth-rpm'


  - stage: SignArtifacts
    displayName: 'Sign Artifacts'
    dependsOn: BuildPackages
    condition: succeeded('BuildPackages')
    jobs:
      - job: SignArtifacts
        timeoutInMinutes: 120

        pool:
          vmImage: 'ubuntu-22.04'

        steps:
          - checkout: none

          # download artifacts that need to be published
          - task: DownloadBuildArtifacts@1
            displayName: 'Download DEB Artifacts'
            inputs:
              ArtifactName: 'azfilesauth-deb'
              downloadPath: $(Build.ArtifactStagingDirectory)

          # - task: DownloadBuildArtifacts@1
          #   displayName: 'Download RPM Artifacts'
          #   inputs:
          #     ArtifactName: 'azfilesauth-rpm'
          #     downloadPath: $(Build.ArtifactStagingDirectory)

          - script: |
              sudo ls -lRt $(Build.ArtifactStagingDirectory)
            displayName: 'List Artifacts'

          - script: |
              sudo apt -y update
              wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
              sudo dpkg -i packages-microsoft-prod.deb
              sudo apt update
              sudo apt install apt-transport-https -y
              sudo apt install dotnet-sdk-9.0 -y
            displayName: "Update dependencies"
          
          - task: EsrpCodeSigning@5
            displayName: 'ESRP CodeSigning MI DEB'
            inputs:
              ConnectedServiceName: 'AzFilesAuthenticator-wif'
              AppRegistrationClientId: '$(AppRegistrationClientId)'
              AppRegistrationTenantId: '$(AppRegistrationTenantId)'
              EsrpClientId: '$(AppRegistrationClientId)'
              UseMSIAuthentication: true
              AuthAKVName: '$(AuthAKVName)'
              AuthSignCertName: '$(AuthSignCertName)'
              FolderPath: '$(Build.ArtifactStagingDirectory)/azfilesauth-deb'
              Pattern: '*.deb'
              signConfigType: 'inlineSignParams'
              inlineOperation: |
                [
                {
                  "KeyCode": "CP-450779-Pgp",
                  "OperationCode": "LinuxSign",
                  "ToolName": "sign",
                  "ToolVersion": "1.0",
                  "Parameters": {}
                }
                ]
              SessionTimeout: '90'
              MaxConcurrency: '25'
              MaxRetryAttempts: '5'
              PendingAnalysisWaitTimeoutMinutes: '5'
              VerboseLogin: true

          # - task: EsrpCodeSigning@5
          #   displayName: 'ESRP CodeSigning MI RPM'
          #   inputs:
          #     ConnectedServiceName: 'AzFilesAuthenticator-wif'
          #     AppRegistrationClientId: $(AppRegistrationClientId)
          #     AppRegistrationTenantId: $(AppRegistrationTenantId)

          #     UseMSIAuthentication: true
          #     AuthAKVName: $(AuthAKVName)
          #     AuthSignCertName: $(AuthSignCertName)

          #     FolderPath: $(Build.ArtifactStagingDirectory)/azfilesauth-rpm
          #     Pattern: '*.rpm'
          #     SessionTimeout: 90
          #     ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2'
          #     MaxConcurrency: 25
          #     signConfigType: inlineSignParams
          #     VerboseLogin: true
          #     inlineOperation: |
          #       [
          #       {
          #         "KeyCode": "CP-450779-Pgp",
          #         "OperationCode": "LinuxSign",
          #         "ToolName": "sign",
          #         "ToolVersion": "1.0",
          #         "Parameters": {}
          #       }
          #       ]

          - script: |
              echo "Listing unsigned artifacts in the staging directory..."
              ls $(Build.ArtifactStagingDirectory)
              chmod 755 $(Build.ArtifactStagingDirectory)/azfilesauth-deb/*.deb
              # chmod 755 $(Build.ArtifactStagingDirectory)/azfilesauth-rpm/*.rpm
              mkdir -p $(Build.ArtifactStagingDirectory)/signed
              cp $(Build.ArtifactStagingDirectory)/azfilesauth-deb/*.deb $(Build.ArtifactStagingDirectory)/signed
              # cp $(Build.ArtifactStagingDirectory)/azfilesauth-rpm/*.rpm $(Build.ArtifactStagingDirectory)/signed
            displayName: 'Prepare Signed Artifacts'
          
          - script: |
              echo "Listing Signed Artifacts..."
              ls -R $(Build.ArtifactStagingDirectory)/signed/
            displayName: 'List Signed Artifacts'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Signed Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/signed'
              ArtifactName: 'azfilesauth-signed'

  - stage: PublishPackages
    displayName: 'Publish Artifacts'
    dependsOn: SignArtifacts
    condition: succeeded('SignArtifacts')
    jobs:
      - job: BuildEV2Artifacts
        timeoutInMinutes: 120

        pool:
          vmImage: 'ubuntu-22.04'
          container: ubuntu:20.04

        steps:
          - checkout: self
            path: AzFilesAuthenticator
            displayName: 'Checkout Repository'

          # download artifacts that need to be published
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Signed Artifacts'
            inputs:
              ArtifactName: 'azfilesauth-signed'
              downloadPath: $(Build.ArtifactStagingDirectory)

          - task: UsePythonVersion@0
            displayName: 'Use Python 3.8'
            inputs:
              versionSpec: 3.8

          - task: PipAuthenticate@1
            displayName: 'Pip Authenticate'
            inputs:
              artifactFeeds: 'One/AzFilesAuthenticator'
          
          - task: AzureCLI@2
            displayName: 'Test PMC installation'
            inputs:
              addSpnToEnvironment: true
              azureSubscription: 'AzFilesAuthenticator-wif'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Build.ArtifactStagingDirectory)/
              inlineScript: |
                pmc --version
                pmc --auth-type wif --base-url "https://pmc-ingest.trafficmanager.net/api/v4" repo list --limit 1
                if [ $? -ne 0 ]; then
                  exit 1
                fi
                pwd
                ls
                find . -type f

          
      #     - task: DownloadSecureFile@1
      #       name: settings
      #       inputs:
      #         secureFile: 'AzFilesAuthenticator_settings.toml'
      #       displayName: 'Download PMC Config File'

      #     - task: DownloadSecureFile@1
      #       name: serviceModel
      #       inputs:
      #        secureFile: 'AzFilesAuthenticator_ServiceModel.Prod.json'
      #       displayName: 'Download EV2 Scope Bindings'

      #     - task: DownloadSecureFile@1
      #       name: scopebindings
      #       inputs:
      #        secureFile: 'AzFilesAuthenticator_scopebindings.json'
      #       displayName: 'Download EV2 Scope Bindings'

      #     - bash: |
      #         EV2_DIR="$(Build.SourcesDirectory)/deploy/EV2_PMC"
      #         SHEXT_BUNDLE_DIR="$EV2_DIR/ServiceGroupRoot/Packages/ShellExt"
      #         cp $(scopebindings.secureFilePath) "$EV2_DIR/ServiceGroupRoot/ScopeBindings.Prod.json"
      #         cp $(serviceModel.secureFilePath) "$EV2_DIR/ServiceGroupRoot/ServiceModel.Prod.json"
              
      #         echo "1) Get pmc-cli"
      #         cd "$SHEXT_BUNDLE_DIR"
      #         mkdir python_dl
      #         pip3 download -d python_dl pmc-cli 
      #         # --python-version 3.8 --implementation cp --platform manylinux2014_x86_64 --abi cp38

      #         echo "2) Copy built DEB packages"
      #         # assuming ESRP signed packages are here:
      #         cd "$(Build.ArtifactStagingDirectory)/azfilesauth-signed"
      #         mkdir "$SHEXT_BUNDLE_DIR/packages"
      #         cp -v *.deb "$SHEXT_BUNDLE_DIR/packages/"

      #         echo "3) Archive for the ShellExt bundle"
      #         cd "$SHEXT_BUNDLE_DIR"
      #         cp $(settings.secureFilePath) ./settings.toml
      #         tar cvf pmc_packages.tar start.sh settings.toml packages python_dl
      #         ls -al

      #         echo "4) Copy EV2 files to artifacts staging"
      #         cp -rv "$EV2_DIR" "$(Build.ArtifactStagingDirectory)/"

      #     - task: PublishBuildArtifacts@1
      #       displayName: 'Publish EV2_PMC Artifacts'
      #       inputs:
      #         PathtoPublish: '$(Build.ArtifactStagingDirectory)/EV2_PMC'
      #         ArtifactName: 'EV2_PMC'

      # - job: Ev2Rollout
      #   displayName: 'EV2 Rollout'
      #   pool: 
      #     type: release
      #   dependsOn: BuildEV2Artifacts
      #   steps:
      #     - task: DownloadBuildArtifacts@1
      #       displayName: 'Download PMC Artifacts'
      #       inputs:
      #         ArtifactName: 'ev2_pmc'
      #         downloadPath: $(Build.ArtifactStagingDirectory)
      #     - task: Ev2RARollout@2
      #       inputs:
      #         EndpointProviderType: 'ApprovalService'
      #         ApprovalServiceEnvironment: 'Production'
      #         TaskAction: 'registerAndRollout'
      #         ServiceRootLocation: 'LinkedArtifact'
      #         ServiceRootPath: '$(Build.ArtifactStagingDirectory)/EV2_PMC/ServiceGroupRoot'
      #         RolloutSpecPath: '$(Build.ArtifactStagingDirectory)/EV2_PMC/ServiceGroupRoot/RolloutSpec.Prod.json'
      #         StageMapName: 'Microsoft.Azure.SDP.Standard'
      #         Select: regions('northeurope')
      #         UseServerMonitorTask: true
      #         ValidateOnly: false
              


  
